### ISSUE TITLE
`sideEffects` isn't necessarily a boolean

### ISSUE THREAD

**Issue by Sec-ant** [velut/zod-package-json#5]
For example, when working with `webpack`, `sideEffects` can also be an array: https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

**Comment by velut** [comment]
Thank you for the issue and the reference link @Sec-ant!

Type of `sideEffects` was changed from `boolean | undefined` to `boolean | string[] | undefined` in v1.0.3.

**Comment by Sec-ant** [comment]
Thank you for the quick fix! We're using a tool [`pkg-pr-new`](https://github.com/stackblitz-labs/pkg.pr.new) that depends on [`query-registry`](https://github.com/velut/query-registry) which in turn depends on this one. Is there an ETA when this fix will be integrated into `query-registry`?

**Comment by velut** [comment]
@Sec-ant I've released `query-registry@3.0.1` with updated dependencies.
